### ISSUE TITLE
getRawPosition() returns a short?

### ISSUE THREAD

**Issue by 5nyper** [alexhenning/I2CEncoder#3]
When Serial printing the value given by getRawPosition(), the value negates from the MAX of int type short. so when it hits the MAX of short, it then becomes the MIN of short.

**Comment by alexhenning** [comment]
It returns a long, see https://github.com/alexhenning/I2CEncoder/blob/master/I2CEncoder.cpp#L97, but it does negate if is_reversed is true https://github.com/alexhenning/I2CEncoder/blob/master/I2CEncoder.cpp#L108.

**Comment by 5nyper** [comment]
I get that, but its not even reversing when its negative

**Comment by alexhenning** [comment]
Then what is the problem? Could you provide more details?

**Comment by 5nyper** [comment]
I'll try to explain how this issue occurs as best as I can:

1. I run the program that spins the motor clockwise for about 3 minutes, printing out its Position using `getRawPosition` to the Serial Monitor

2. as the position gets over `32767`, it then becomes `-32767` and counts up

That is really all I can provide, the issue is strange.

**Comment by alexhenning** [comment]
Given the fact that it is reading straight from the encoder, I doubt this is a bug in this code, but rather the encoder itself uses a 16-bit integer internally to count. It would be possible to implement a smart wrapper that keeps track of the number of times you've wrapped around, as long as you update frequently. Unfortunately, I don't have access to these encoders anymore.

**Comment by 5nyper** [comment]
Okay, Thanks for the help!
