### ISSUE TITLE
No values

### ISSUE THREAD

**Issue by osimon8** [alexhenning/I2CEncoder#4]
Hello,

I just installed your library and am trying to use it, but when I try to read values from my encoder, I just get 0. It is a 393, and has never been used before. I saw on the documentation for the encoder that it has to be "setup" somehow, but I cannot find out how to do that anywhere. Thanks!

**Comment by alexhenning** [comment]
@osimon8 I'm not sure what setup your referring to, you have to set it up mechanically[1] and wire it, but it's software state resets each time and you have to reinitialize it[2]:

> When the encoder receives power it starts up. It does not retain it’s previous address, position or most other data from before it was powered down. When it comes back on, it is set to a default address. To initialize the device, it must be assigned a new address. Once it has been assigned an address it is said to be initialized. From this point, you can read it’s speed, position and change other configuration options. The most important configuration to make sure you change when necessary is to disable the termination of the encoder if there are any other I2C devices after the encoder. Otherwise, you can’t communicate with them. If the next device is an encoder, you just repeat this process to initialize it too. As a result of this initialization process, the order you plug encoders into each other is very important.

Other than that, it should just work. Are you trying the code from single encoder example[3]? If so, you'll have to rotate the motor manually for the value to change.

[1] http://www.robotc.net/blog/wp-content/uploads/2012/02/393.pdf
[2] https://github.com/alexhenning/I2CEncoder#initialization
[3] https://github.com/alexhenning/I2CEncoder/blob/master/examples/Single_Encoder/Single_Encoder.ino

**Comment by osimon8** [comment]
Thanks for the reply! It seems to be working now, thanks for the help!
