### ISSUE TITLE
Use of two or more encoders

### ISSUE THREAD

**Issue by Tamires04santos** [alexhenning/I2CEncoder#6]
Hi!

I found this library incredible, I did some tests and it worked very well.
I would like to know if you ever used this library with two or more encoders?

Thank you!!

**Comment by alexhenning** [comment]
Yes, it supports daisy chaining multiple encoders. [This file](https://github.com/alexhenning/I2CEncoder/blob/master/examples/Feet_per_Second/Feet_per_Second.ino) has an example of using two encoders.

**Comment by Tamires04santos** [comment]
Thank you so much for the information!!


However, I'm having a problem, when I run the code and put the leftEncoder.getSpeed() and rightEncoder.getSpeed() variables to print, the values are changed in just one variable, even triggering the two encoders. For example, if I trigger the left and right encoder, I only have values in the leftEncoder.getSpeed() variable, while the rightEncoder.getSpeed() variable is at zero.
The encoder connection looks like this image:
![i2c](https://user-images.githubusercontent.com/26287951/207063951-9bef274a-61f1-4e0d-b135-23c5c8e6e9c2.png)

**Comment by Tamires04santos** [comment]
I managed to find my error. I was connecting the encoders incorrectly. What helped me was this image:
https://jpearman.smugmug.com/Robotics/Misc/i-ccMBMv8/0/S/i2c_ime_chain-S.jpg
Again, thank you very much!!

**Comment by alexhenning** [comment]
@Tamires04santos I'm glad you solved the issue!
